project:
  type: website

website:
  title: "Luoning Zhang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
  page-footer:
    center: |
      _This personal website is built using [Quarto](https://quarto.org), an open-source scientific and technical publishing system._

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true