---
title: "Research"
---

### Optimizing Large Language Model (LLM) and Reinforcement Learning (RL) Methods to Explore Open Problems in Combinatorics
*March 2025 – Ongoing*  

**Mentored by** [Prof. Nathan Kaplan](https://www.math.uci.edu/~nckaplan/). | **Collaborated with** [Xu Zhuang](https://zxmath.github.io/), and [Tianhao Wang](https://tianhaow.github.io/).  


[Demo Game](https://luoninz1.github.io/N3il_Board_Game/){.btn .btn-primary .me-2}

- Implemented Monte Carlo Tree Search (MCTS) and Neural Networks to explore the largest and smallest complete sets, and optimized the algorithm’s time complexity through algorithmic improvements and Numba acceleration, boosting performance from ~7 iter/s to 15,000+ iter/s.  
- For $n = 58 \dots 72$, the algorithm finds **$1.8n \pm 2$** points, which outperforms the previous best lower bound: $(1.5 - \varepsilon) n$. Based on the observed trend, the bound appears to asymptotically approach $1.8n$ for larger $n$.
- Optimizing an AlphaZero-based reinforcement learning framework, focusing on state encoding, network architecture, hyperparameter tuning, and data augmentation.
- Exploring the smallest geometric dominating set and complete set; developing graph search algorithms.  
- Investigating LLM-based methods for code optimization to explore open problems in combinatorics.  

### Optimizing Large Language Models (LLM) for Academic Support: A Framework for Knowledge Graph (KG) Embedding and “Cheat Sheet” Generation
*September 2024 – Ongoing*  

**Mentored by** [Prof. Hengrui Cai](https://hengruicai.github.io/). | **Collaborated with** Yanjun He, Jiaye Liu, and Xinrui Fu.  

[Symposium Poster (Interim Presentation)](urop-symposium.html){.btn .btn-primary .me-2}

- Designed a benchmark to evaluate the performance of LLMs on college-level academic problems.  
- Integrated knowledge graphs (KG) for Retrieval-augmented Generation into LLMs and assessed accuracy improvements on the benchmark.  

### Instantaneous Electromagnetic Water Heater Design and Multiphysics Field Finite Element Optimization
*August 2016 – October 2017*  
- Designed the structure and circuitry of an induction water heater with improved energy efficiency and temperature stability.  
- Coded a program for temperature control and user interaction on Arduino.  
- Optimized energy efficiency by applying thermodynamic and electromagnetic models and conducting multiphysics finite element simulations in ANSYS.  
- Applied and accepted as **Patent Number: ZL201621267831.6**.
